language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "teemoo7-github"
script:
  - xvfb-run make test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
