language: java
jdk:
  - openjdk17
addons:
  sonarcloud:
    organization: "teemoo7-github"
dist: xenial
services:
  - xvfb
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
